-- Seed the real Major/Minor task data from fall-bingo-2026.xlsx.
--
-- 114 Majors (tile_sequence 1..114, board order from the "Major Tasks" sheet)
-- and 61 Minors (shared pool, tile_sequence null, from the "Minor Tasks"
-- sheet). Major #58, "Yama is blocking the path! What will you do?", is the
-- doomsday tile.
--
-- Run against BOTH schemas, e.g.:
--   mysql candyland      < 2026-09-16_seed_task_data.sql
--   mysql candyland_test < 2026-09-16_seed_task_data.sql
--
-- Precondition: task table is empty on both schemas (PR #44 seeded zero
-- rows). Confirm with `select count(*) from task;` before running.

-- Majors
insert into task (kind, tile_sequence, title, task, notes) values
  ('major', 1, 'Huey Mass Event', 'Obtain 6 Hueycoatl hides.', 'All teams play MUST play together on **W495** in one mass lobby. You can only split into smaller groups after the first Hueycoatl hide drop!'),
  ('major', 2, 'It''s time for Castle Wars.', 'Your entire team must Green Log the Castle Wars collection log.', 'You''ll understand this if you watched the technical demo and know how /candyland roll works.'),
  ('major', 3, 'Listen, we''re putting together a crew...', 'Complete each raid 1 time.', 'If a team has multiple inexperienced players, these are allowed: Entry mode Theatre of Blood, Entry mode Tombs of Amascut'),
  ('major', 4, 'Welp... we''re boned', 'Obtain 2 Bone Sceptre''s and 2 scurrius spines.', null),
  ('major', 5, 'A Royal Tribute', 'Obtain 1 of the following Royal Titans uniques: Fire Element Staff Crown, Ice Element Staff Crown, Deadeye prayer scroll, Mystic Vigour prayer scroll, Pet', 'This does not include: Giantsoul amulet, Dessicated pages'),
  ('major', 6, 'Why is that cow over there in a pool?', 'Obtain the Beef pet.', null),
  ('major', 7, 'Sacrifice an Ultimate Ironman', 'Obtain any Zulrah unique.', 'This does not include: Zul-andra teleport, Zulrah''s scales'),
  ('major', 8, 'Momma needs a new handbag', 'Obtain the Immaculate Mole skin and the Pristine Spider silk.', 'Don''t worry, it''s possible to obtain these after already getting them.'),
  ('major', 9, 'Being a hero sometimes requires stealing...', 'Fill a Stash Unit: Fountain of Heroes (Elite)', 'All items must be dropped by an npc, or crafted through raw materials you obtain. Items required: Dragon boots, Splitbark legs, Rune longsword'),
  ('major', 10, 'Things are heating up!', 'Obtain the Fire Element Staff Crown from Branda.', 'Everyone targets Branda!'),
  ('major', 11, 'OMG who turned on the air conditioning!!', 'Obtain the Ice Element Staff Crown from Eldric.', 'Everyone targets Eldric!'),
  ('major', 12, 'Wake up! Grab a brush and put a little makeup!', 'Obtain 2 Awakener''s orbs.', 'Player''s choice.'),
  ('major', 13, 'A Song of Ice and Fire', 'Obtain the Pet OR both of the Ice and Fire Element Staff Crown pieces.', 'Split your team between Fire and Ice, or tackle one at a a time!'),
  ('major', 14, 'Listen, we''re putting together a crew...', 'Complete each raid 1 time.', 'If a team has multiple inexperienced players, these are allowed: Entry mode Theatre of Blood, Entry mode Tombs of Amascut'),
  ('major', 15, 'Babe... I want to go ring shopping!!', 'Obtain any 2 rings from the Dagganoth Kings.', 'Duplicates are allowed on THIS tile.'),
  ('major', 16, 'The Jewlery Thief', 'Obtain any 3 rings from the Dagganoth Kings.', 'Duplicates are allowed on THIS tile.'),
  ('major', 17, 'What can I say, we''re good in the sac', 'Obtain 10 Giant Egg Sacs.', null),
  ('major', 18, 'CHAAARGE!', 'Obtain 1 unique drop from General Graardor.', 'This does not include: Godsword Shards (1, 2, 3), Frozen key pieces'),
  ('major', 19, 'Scavenger hunt!!', 'Fill a Stash Unit: Next to Miss Schism (Master)', 'All items must be dropped by an npc, purchased from a base shop stock, or crafted through raw materials you obtain. Items required: Abyssal Whip, Cape of Legends, Spined Chaps'),
  ('major', 20, 'Queen Black Dragon when?', 'Cut off the King Black Dragon''s heads.', 'Obtain either the Kbd heads or the Draconic visage.'),
  ('major', 21, 'Ask Bird if you can borrow one?', 'Obtain any Crystal seed.', 'This includes the following: Enhanced, Weapon, Armor, Tool'),
  ('major', 22, 'Temple of Lost Ancients', 'Obtain any 2 Godwars Dungeon uniques.', 'This does not include: Godsword Shards (1, 2, 3), Ancient Ceremonial pieces, Nihil shards, Frozen key pieces, Ecumenical key shards'),
  ('major', 23, 'There''s always time to smell the flowers!', 'Obtain a Lily of the Sands drop from the Tombs of Amascut.', 'This includes all difficulty levels.'),
  ('major', 24, 'You can Fall on me with grace...', 'Obtain 1 Mad Angel unique.', 'This does not include: Ardeaglais teleport, Granite dust'),
  ('major', 25, 'Steal from Semour''s Wife', 'Obtain 1 unique drop from Commander Zilyana.', 'This does not include: Godsword Shards (1, 2, 3), Frozen key pieces');

insert into task (kind, tile_sequence, title, task, notes) values
  ('major', 26, 'What can I say, we''re good in the sac', 'Obtain 10 Giant Egg Sacs.', null),
  ('major', 27, 'Queen of the Swamp', 'Obtain 1 Zulrah unique.', 'This does not include: Zul-andra teleport, Zulrah''s scales'),
  ('major', 28, 'Listen, we''re putting together a crew...', 'Complete each raid 1 time.', 'If a team has multiple inexperienced players, these are allowed: Entry mode Theatre of Blood, Entry mode Tombs of Amascut'),
  ('major', 29, 'Sir Tiffy Cashien fucking wishes...', 'Fill a Stash Unit: Civitas illa Fortis (Elite)', 'You must obtain any piece of Sunfire Fanatic armour.'),
  ('major', 30, 'Back to the Mountain already?', 'Fill a Stash Unit: Salvager Overlook (Master)', 'Obtain 3 Hueycotal hides.'),
  ('major', 31, 'Momma needs a new handbag', 'Obtain the Immaculate Mole skin and the Pristine Spider silk.', null),
  ('major', 32, 'Scorching Bow is a very balanced weapon', 'Obtain 2 unique drops from K''ril Tsutsaroth.', 'This does not include: Godsword Shards (1, 2, 3), Frozen key pieces'),
  ('major', 33, 'The Ancient War rages on...', 'Obtain any 2 Godwars Dungeon uniques.', 'This does not include: Godsword Shards (1, 2, 3), Ancient Ceremonial pieces, Nihil shards, Frozen key pieces, Ecumenical key shards'),
  ('major', 34, 'I need another energy drink, brb...', 'Obtain 2 Awakener''s orb.', null),
  ('major', 35, 'Powered staved don''t charge themselves!', 'Obtain 1 Cache of runes.', null),
  ('major', 36, 'Not exactly the purples I had in mind...', 'Obtain 4 purple items from the Phantom Muspah.', 'This does not include: Ancient essence, Ancient brew'),
  ('major', 37, 'Oh boy what''s in here', 'Kill 1 Mimic', null),
  ('major', 38, 'In need of a transfusion...', 'Obtain 69 Vials of Blood from the Theatre of Blood.', 'This includes all difficulty levels.'),
  ('major', 39, 'Are you not entertained!?', 'Obtain 1 Fortis Colosseum unique.', 'This does not include: Dizana''s quiver'),
  ('major', 40, 'These still aren''t the purples I had in mind...', 'Obtain 4 purple items from the Phantom Muspah.', 'This does not include: Ancient essence, Ancient brew'),
  ('major', 41, 'Listen, we''re putting together a crew...', 'Complete each raid 1 time.', 'If a team has multiple inexperienced players, these are allowed: Entry mode Theatre of Blood, Entry mode Tombs of Amascut'),
  ('major', 42, 'The Great Wall of Fire', 'Obtain a number of Fire capes equal to: (Team size - 3)', 'Good luck on your new personal best and Jad coming home with you!'),
  ('major', 43, 'The Great Wall of Fire', 'Obtain a number of Fire capes equal to: (Team size - 3)', 'Good luck on your new personal best and Jad coming home with you!'),
  ('major', 44, 'The Great Wall of Fire', 'Obtain a number of Fire capes equal to: (Team size - 3)', 'Good luck on your new personal best and Jad coming home with you!'),
  ('major', 45, 'The bird is the word', 'Obtain 1 unique drop from Kree''arra.', 'This does not include: Godsword Shards (1, 2, 3), Frozen key pieces'),
  ('major', 46, 'Locked and Loaded', 'Obtain 2,000 cannonballs or a unique from Corporeal Beast.', null),
  ('major', 47, 'Queen of the Swamp', 'Obtain 1 Zulrah unique.', 'This does not include: Zul-andra teleport, Zulrah''s scales'),
  ('major', 48, 'Chop chop!', 'Fill a Stash Unit: Enchanted Valley (Master)', 'You must obtain a Dragon Axe.'),
  ('major', 49, 'Wilderness Timeshare Retreat', 'Fill a Stash Unit: Soul Altar (Master)', 'All items must be dropped by an npc, purchased from a base shop stock, or crafted through raw materials you obtain. Items required: Dragon pickaxe, Helm of Neitiznot, Rune boots'),
  ('major', 50, 'Listen, we''re putting together a crew...', 'Complete each raid 1 time.', 'If a team has multiple inexperienced players, these are allowed: Entry mode Theatre of Blood, Entry mode Tombs of Amascut');

insert into task (kind, tile_sequence, title, task, notes) values
  ('major', 51, 'Butch, why won''t you come home with me?', 'Obtain 1 unique item from Vardorvis.', 'This includes: Chromium ingot, Ring progress roll, Vestige, Virtus, Axe piece, Pet'),
  ('major', 52, 'Telef''s Frozen Prison', 'Obtain 1 unique item from Duke Sucellus.', 'This includes: Chromium ingot, Ring progress roll, Vestige, Virtus, Axe piece, Pet'),
  ('major', 53, 'Any Awakened Leviathan enjoyers?', 'Obtain 1 unique item from The Leviathan.', 'This includes: Chromium ingot, Ring progress roll, Vestige, Virtus, Axe piece, Pet'),
  ('major', 54, 'Yat honey... Do you miss me?.. Come back to me, Yat...', 'Obtain 1 unique item from The Whisperer.', 'This includes: Chromium ingot, Ring progress roll, Vestige, Virtus, Axe piece, Pet'),
  ('major', 55, 'Burn it all down!', 'Obtain 8 items from subuding the Wintertodt.', 'Duplicates allowed, the list includes: Bruma torch, Warm gloves, Pyromancer outfit, Tome of Fire, Dragon axe, Phoenix'),
  ('major', 56, 'Tooth Fairy? Is that you?', 'Obtain a Lizardman Fang drop from the Chambers of Xeric.', 'This includes all difficulty levels.'),
  ('major', 57, 'Take a page out of my book!', 'Fill a Stash Unit: Edgeville Monastary** (Elite)', 'Items required: 4 God book pages of the same god, duplicates included.'),
  ('major', 58, 'Yama is blocking the path! What will you do?', 'Obtain 1 piece of Oathplate equipment.', 'This includes: Oathplate helm, Oathplate chest, Oathplate legs, Oathplate shards (450 total)'),
  ('major', 59, 'Gearing up for the mid game!', 'Obtain 4 unique items from Moons of Peril.', 'Four total Moon item drops; duplicates count.'),
  ('major', 60, 'Hey this is pretty good...', 'Obtain 1 Moons of Peril weapon drop.', 'Atlatl, Macuahuitl, or Blue moon spear.'),
  ('major', 61, 'I miss Obelisk the Tormentor...', 'Obtain a Tormented Synpase or Burning Claw.', null),
  ('major', 62, 'Stop monkeying around!', 'Obtain 1 unique item from Demonic Gorillas.', 'This includes: Zenyte shards, Ballista limbs, Ballista spring, Light frame, Heavy frame, Monkey tail'),
  ('major', 63, 'Stop monkeying around!', 'Obtain 2 unique items from Demonic Gorillas.', 'This includes: Zenyte shards, Ballista limbs, Ballista spring, Light frame, Heavy frame, Monkey tail'),
  ('major', 64, 'The reason Laz didn''t play Bingo with us...', 'Obtain 3 unique items from Demonic Gorillas.', 'This includes: Zenyte shards, Ballista limbs, Ballista spring, Light frame, Heavy frame, Monkey tail'),
  ('major', 65, 'Don''t get my hair wet Tempy!!!', 'Obtain 2 Tempoross unique rolls.', 'Receiving 25 Soaked pages is a replacement roll for a unique, this counts as well.'),
  ('major', 66, 'Who''s got the Swag Socks?', 'Obtain any medium-clue boots.', 'This includes: Ranger, Wizard, Manacles, Holy sandals, or Climbing Boots (g)'),
  ('major', 67, 'It''s just like a huge chicken drumstick!', 'Obtain a Sarachnis Cudgel.', null),
  ('major', 68, 'Listen, we''re putting together a crew...', 'Complete each raid 2 times.', 'For ToA you must be above invocation 150.'),
  ('major', 69, 'Just one more floor...', 'Obtain 1 unique from the Doom of Mokhaiotl.', 'Receiving the pet counts for this task.'),
  ('major', 70, 'The Ancient Prison', 'Obtain 1 unique item from Nex.', 'This does not include: Ancient Ceremonial pieces, Nihil shards, Ecumenical key shards'),
  ('major', 71, 'The Ancient Prison', 'Obtain 1 unique item from Nex.', 'This does not include: Ancient Ceremonial pieces, Nihil shards, Ecumenical key shards'),
  ('major', 72, 'Bird''s favorite item sprite', 'Obtain 1 Crystal armour seed.', null),
  ('major', 73, 'King Black Dragon''s cousin Vinny', 'Obtain 3 Vorkath heads.', null),
  ('major', 74, 'Queen of the Swamp', 'Obtain 2 Zulrah uniques.', 'This does not include: Zul-andra teleport, Zulrah''s scales'),
  ('major', 75, 'Take your Pick.', 'Obtain a Dragon pickaxe or 2 Dragon axes.', 'Your choice.');

insert into task (kind, tile_sequence, title, task, notes) values
  ('major', 76, 'Listen, we''re putting together a crew...', 'Complete each raid 2 times.', 'For ToA you must be above invocation 150.'),
  ('major', 77, 'May Elidinis guide you...', 'Receive 1 purple from the Tombs of Amascut.', null),
  ('major', 78, 'Wait... this isn''t TOA...', 'Fill a Stash Unit: Pyramid Plunder (Master)', 'All items must be dropped by an npc, purchased from a base shop stock, or crafted through raw materials you obtain. Items required: Pharoah''s sceptre, Menaphite Robe set'),
  ('major', 79, 'What do you mean this is only a spec weapon?', 'Obtain 1 unique from the Maggot King.', 'This includes: Elder venator fang, Crimson kisten, Pet'),
  ('major', 80, 'Steal from Joe''s toilet paper storage', 'Obtain 1 purple from the Chambers of Xeric.', null),
  ('major', 81, 'Gary Gilbert could never', 'Obtain an Obor''s club or Bryophyta''s essence.', null),
  ('major', 82, 'Shiny Magikarp', 'Obtain 1 Golden tench.', null),
  ('major', 83, 'Oh boy what''s in here', 'Kill 2 Mimics.', null),
  ('major', 84, 'They added the plumbus to the game!!', 'Obtain 1 Dragon hunter wand.', null),
  ('major', 85, 'The clan needs you to kidnap more Verzik pets...', 'Obtain 1 purple from the Theare of Blood.', null),
  ('major', 86, 'We''re starting our very own library!', 'Obtain 1 book that give''s Magic % damage.', 'This includes: Mage''s book, Tome of Fire, Tome of Water, Tome of Earth'),
  ('major', 87, 'The Executioner', 'Obtain 1 rare Vardorvis unique.', 'This includes: Chromium ingot, Ring progress roll, Vestige, Virtus, Axe piece, Pet'),
  ('major', 88, 'The Commander', 'Obtain 1 rare Duke Sucellus unique.', 'This includes: Chromium ingot, Ring progress roll, Vestige, Virtus, Axe piece, Pet'),
  ('major', 89, 'The Creature', 'Obtain 1 rare Whisperer unique.', 'This includes: Chromium ingot, Ring progress roll, Vestige, Virtus, Axe piece, Pet'),
  ('major', 90, 'The Assassin', 'Obtain 1 rare Leviathan unique.', 'This includes: Chromium ingot, Ring progress roll, Vestige, Virtus, Axe piece, Pet'),
  ('major', 91, 'Damn them! Damn them to hell!', 'Fill a Stash Unit: Catacomb of Kourend (Master)', 'All items must be dropped by an npc, purchased from a base shop stock, or crafted through raw materials you obtain. Items required: Tormented Synapse, Amulet of the Damned'),
  ('major', 92, 'Which God will bestow their favor?', 'Obtain 1 piece of God D'' Hide equipment.', null),
  ('major', 93, 'Lord of the Rings', 'Obtain each ring drop from the Dagganoth Kings.', 'This includes: Warrior ring, Berserker ring, Archer ring, Seers ring'),
  ('major', 94, 'I am the captain now.', 'Obtain 4 unique items from any of the Godwars Dungeon bosses.', 'This does not include: Godsword Shards (1, 2, 3), Ancient Ceremonial pieces, Nihil shards, Frozen key pieces, Ecumenical key shards'),
  ('major', 95, 'The Great Wall of Lava', 'Obtain a number of Fire or Infernal capes equal to: (Team size - 3) and atleast one Infernal cape', 'Good luck on your new personal best and a pet coming home with you! Each Infernal cape can substitute a firecape.'),
  ('major', 96, 'The Great Wall of Lava', 'Obtain a number of Fire or Infernal capes equal to: (Team size - 3) and atleast one Infernal cape', 'Good luck on your new personal best and a pet coming home with you! Each Infernal cape can substitute a firecape.'),
  ('major', 97, 'Venny Venny Venator', 'Obtain 2 Venator shards.', null),
  ('major', 98, 'The biggest chicken you''ve ever seen!', 'Obtain 1 Unique from Corporeal Beast.', 'This includes: Spirit Shield, Holy Elixer, Any Sigil, Jar, Pet'),
  ('major', 99, 'A Llama''s Prison', 'Obtain 1 Unique from Corporeal Beast.', 'This includes: Spirit Shield, Holy Elixer, Any Sigil, Jar, Pet'),
  ('major', 100, 'You''re wearing that..... to work?', 'Fill a Stash Unit: Lava Dragon Isle (Master)', 'All items must be dropped by an npc, purchased from a base shop stock, or crafted through raw materials you obtain. Items required: Dragon med helm, Toktz-ket-xil, Brine sabre, Rune platebody, Amulet of glory.');

insert into task (kind, tile_sequence, title, task, notes) values
  ('major', 101, 'Build-A-Moons', 'Obtain a full, matching, Moons of Peril set.', 'Any one full 4-piece Moon set obtained by the team.'),
  ('major', 102, 'Monster Hunter: Rise', 'Build a full Hueycoatl warrior.', 'Obtain enough Hueycoatl hide for the following: Coif, Body, Chaps, and Vambraces'),
  ('major', 103, 'This boss is old enough to drink!', 'Obtain a Dragon chainbody from the Kalphite Queen.', null),
  ('major', 104, 'I''ve got.... a pair of Aces!', 'Obtain 2 of the same crystal seeds.', 'This does not include the crystal acorn.'),
  ('major', 105, 'Kharidian Nights', 'Obtain 1 rare purple frorm Tombs of Amascut.', 'This includes any purple except the Osmumten''s Fang and Lightbearer.'),
  ('major', 106, 'Paradigm of Exodus', 'Obtain 1 rare purple from the Chambers of Xeric.', 'This includes any purple except the Dexterous and Arcane prayer scrolls.'),
  ('major', 107, 'Probita would be proud.', 'Obtain a collection log for a pet.', 'You are not allowed to submit an image for a pet that you already own.'),
  ('major', 108, 'I was being hunted by a DISGUSTING TOXIC PKER in the wilderness and I was skull tricked by them because they told me to turn off skull prevention options and click on them for the video. I, as a defenseless PVMer, obliged and consequently was risking...', 'Obtain 1 Voidwaker piece or Revenant Weapon attachment.', 'You should try the multi bosses with your team!'),
  ('major', 109, 'NIGHTMARE NIGHTMARE NIGHTMARE', 'Obtain 1 unique item from either Nightmare.', 'This does not include the Sleepy tablet.'),
  ('major', 110, 'The prison of Icec', 'Obtain 1 unique item from Nex.', 'This does not include: Ancient Ceremonial pieces, Nihil shards, Ecumenical key shards'),
  ('major', 111, 'It''s doomed.', 'Obtain 1 unique from the Doom of Mokhaiotl.', 'This does not include the pet.'),
  ('major', 112, 'The Tale of Serafina', 'Obtain 1 rare purple from the Theatre of Blood.', 'This does not include the Avernic hilt.'),
  ('major', 113, 'Welcome back 👹', 'Obtain 1 piece of Oathplate equipment.', 'This does not have a shard mercy rule.'),
  ('major', 114, 'Purple Rain - Prince', 'Obtain 1 purple from each raid or any Megarare.', 'The Final Tile. Thanks for playing! Receive 1 purple item from each raid, or any Megarare.');

-- Minors
insert into task (kind, tile_sequence, title, task, notes) values
  ('minor', null, 'The Forest Snapchat Group', 'Take a selfie at 5 different Forestry event types.', 'You must include at least one screenshot of each different event type you visit.'),
  ('minor', null, 'Why fletch?', 'Subdue the Wintertodt 12 times.', 'If multiple players want to do this, you must be in the same world and game together.'),
  ('minor', null, 'What''s hotter than Volcano?', 'Kill Zalcano 12 times.', 'If multiple players want to do this, you must be in the same world and game together.'),
  ('minor', null, 'I hope it doesn''t erupt....', 'Earn 12,000 Volcanic Mine points.', 'This is cumulative, the more players who participate the faster it will be.'),
  ('minor', null, 'I see a storm coming....', 'Subdue Tempoross 12 times.', 'If multiple players want to do this, you must be in the same world and game together.'),
  ('minor', null, 'White Water Rafting', 'Board a RAFT from Catherby. Without stepping back on land, you need to catch 2 of each of the following fish off your boat:Raw Lobster, Raw Tuna, Raw Swordfish, Raw Mackerel, Raw Cod, Raw Bass, Raw Shark, Raw Karambwan, Raw Shrimps, Raw Anchovies, Raw Sardine, Raw Herring', 'You must take a picture at each Boat Fishing Spot. After you''ve caught all the fish, you must also take a selfie with the Wizard''s Tower in the background and each fish in your inventory. Hope you have a tacklebox!'),
  ('minor', null, 'Northern Raft Expedition', 'Board a RAFT from Port Piscarilius. Without stepping back on land, you need to catch 5 of each of the following fish off your boat: Raw Anglerfish, Raw Monkfish, Raw Tuna, Raw Swordfish', 'You must take a picture at each Boat Fishing Spot. After you''ve caught all the fish, you must also take a selfie with the Lighthouse in the background and each fish in your inventory. Hope you have a tacklebox!'),
  ('minor', null, 'This isn''t Fishing Trawler....', 'Catch 600 of the highest-level trawling fish YOU can catch.', 'This is cumulative, the more players who participate the faster it will be.'),
  ('minor', null, 'Could I have a go with your bird?', 'Receive 50 Molch Pearls from Aerial Fishing.', 'This is cumulative, the more players who participate the faster it will be.'),
  ('minor', null, 'Hmm... Kovac think it a gut feeling thing...', 'Forge 12 swords in the Giant''s Foundry.', 'This is cumulative, the more players who participate the faster it will be.'),
  ('minor', null, 'They''re building a speed boat!', 'Obtain 2 Normal dragon keel parts as drops.', 'This is cumulative, the more players who participate the faster it will be.'),
  ('minor', null, 'They''re building a yacht!', 'Obtain 1 Large dragon keel parts as a drop.', null),
  ('minor', null, 'Let the Scar be no more!', 'Complete 12 Guardians of the Rift games.', 'If multiple players want to do this, you must be in the same world and game together.'),
  ('minor', null, 'You don''t need to go into the altar!?', 'Gain 20,000 Runecraft XP creating Sunfire runes.', 'This is cumulative, the more players who participate the faster it will be.'),
  ('minor', null, 'Praise the Sun', 'Gain 40,000 Runecraft XP creating Sunfire runes.', 'This is cumulative, the more players who participate the faster it will be.'),
  ('minor', null, 'Shamanism is that you?', 'Fully decorate 16 Vale Totem sites.', 'This is cumulative, the more players who participate the faster it will be.'),
  ('minor', null, 'If a tree can bleed... can it feel pain?', 'Fletch 10,000 Headless seeking arrows.', 'You must collect the blood during this event, the logs and feathers required can be purchased or collected prior.'),
  ('minor', null, 'Jesse, we need to cook.', 'Complete 12 full rounds in Mastering Mixology.', 'Try your best and make all 3 potions in every round!'),
  ('minor', null, 'Who is that guy waving to?', 'Collect 12 Marks of Grace.', 'This is cumulative, the more players who participate the faster it will be.'),
  ('minor', null, 'Pkers and Agility? My favorite!', 'Collect 12 Wilderness Agility tickets without dying.', 'This is cumulative, the more players who participate the faster it will be.'),
  ('minor', null, 'Holy Grave Robbing', 'Search the highest level Hallowed Sepulchre Coffin you can loot 10 times.', 'This is cumulative, the more players who participate the faster it will be.'),
  ('minor', null, 'Prepping for a trip to the Barrows', 'Collect 12 Strange lockpicks from the Hallowed Sepulchre.', 'This is cumulative, the more players who participate the faster it will be.'),
  ('minor', null, 'Spare change.... Spare change please....', 'Collect 120 Hallowed Marks from the Hallowed Sepulchre.', 'This is cumulative, the more players who participate the faster it will be.'),
  ('minor', null, 'Someone call PETA!!', 'Catch 300 Chinchompas of any colour.', 'This is cumulative, the more players who participate the faster it will be.'),
  ('minor', null, 'Don''t forget to pet Guild Hunter Kiko!', 'Complete 12 Rumours for the Hunter Guild.', 'This is cumulative, the more players who participate the faster it will be.');

insert into task (kind, tile_sequence, title, task, notes) values
  ('minor', null, 'Herbie: Fully Loaded', 'Hunt and harvest the Herbiboar 12 times.', 'This is cumulative, the more players who participate the faster it will be.'),
  ('minor', null, 'What are ye doing in me pockets?', 'Receive 12 non-beginner Clues from pickpocketing.', 'This is cumulative, the more players who participate the faster it will be.'),
  ('minor', null, 'Who''s your Mummy?', 'In Pyramid Plunder, loot the furthest Golden Chest you can access 12 times.', 'This is cumulative, the more players who participate the faster it will be.'),
  ('minor', null, 'Catherby Catch N Cook', 'Board a RAFT with a RANGE from Catherby. Without stepping back on land, you need to catch and successfully cook one of each of the following fish on your boat: Raw Lobster, Raw Tuna, Raw Swordfish, Raw Shark, Raw Shrimps', 'Use a facility bottle to swap what is on your raft for a cooking range. Take a picture at the end with 1 of each cooked fish.'),
  ('minor', null, 'Southern Ocean Seafood Boil', 'Board a BOAT with a RANGE from anywhere. Without stepping back on land, you need to catch and successfully cook one of each of the following fish on your boat: Raw Giant Krill, Raw Haddock, Raw Yellowfin, Raw Halibut, Raw Bluefin', 'Use a facility bottle to swap what is on your raft for a cooking range. Take a picture at the end with 1 of each cooked fish.'),
  ('minor', null, 'Getting Ahead', 'Reanimate one Ensouled Head with each tier reanimation spell OUTSIDE of Arceeus.', 'There are 4 different reanimation spells you need to use. You need to get the drop for a head to reanimate it fresh in the location where you killed the monster. You can reanimate the head while it''s on the floor as long as it is fresh. Take a picture of the monster "alive" in each different location.'),
  ('minor', null, 'The Dog Bone industry is booming!', 'Freshly obtain and bury one of each of the following bones: Wyrmling bones, Babydragon bones, Wyrm bones, Strykewyrm bones, Wyvern bones, Dragon bones, Drake bones, Lava dragon bones, Frost dragon bones, Superior dragon bones', 'You must kill the monster and take a picture next to the loot pile and/or of you burying each of the bones. Whichever picture you decide is easier for you to take a picture of you doing it is acceptable.'),
  ('minor', null, 'In Saradomin''s light we pray...', 'Obtain 600,000 Prayer experience.', 'This is cumulative, the more players who participate the faster it will be.'),
  ('minor', null, '126 Combat isn''t going to earn itself!', 'Obtain 1,200,000 Prayer experience', 'This is cumulative, the more players who participate the faster it will be.'),
  ('minor', null, 'We went Easy on you...', 'Find and complete 20 Easy clues.', 'This is cumulative, the more players who participate the faster it will be.'),
  ('minor', null, 'Falador Massacre 2.0', 'Find and complete 10 Medium clues.', 'This is cumulative, the more players who participate the faster it will be.'),
  ('minor', null, 'This shouldn''t be that HARD...', 'Find and complete 6 Hard clues.', 'This is cumulative, the more players who participate the faster it will be.'),
  ('minor', null, 'Who''s your favorite high level boss?', 'Find and complete 2 Elite clues.', 'This is cumulative, the more players who participate the faster it will be.'),
  ('minor', null, 'Watson just placed an order for one of everything!?!', 'Find and complete 1 Master clues.', null),
  ('minor', null, 'I just need to top off my charges...', 'Obtain 6,000 Zulrah scales.', 'This is cumulative, the more players who participate the faster it will be.'),
  ('minor', null, 'Toxic Blowpipe Enthusiast', 'Obtain 12,000 Zulrah scales.', 'This is cumulative, the more players who participate the faster it will be.'),
  ('minor', null, 'I''M AWAKE!!!', 'Obtain 1 Awakener''s Orb from any boss.', null),
  ('minor', null, 'Bling Bling!', 'Obtain 2 Steel rings.', 'This is cumulative, the more players who participate the faster it will be.'),
  ('minor', null, 'Crying Icicles', 'Obtain 240 Frozen tears.', 'This is cumulative, the more players who participate the faster it will be.'),
  ('minor', null, 'The Hash Slinging Slasher', 'Obtain 1 pair of Sulphur blades.', null),
  ('minor', null, 'Stab Stab Stab!', 'Obtain 1 pair of Earthbound tecpatli.', null),
  ('minor', null, 'Is it hot in here or is it just me?', 'Obtain a TzHaar ket-om or a TzHaar xil-ak.', 'You only need to obtain 1 or the other.'),
  ('minor', null, 'I know you haven''t been collecting your White Berries', 'Obtain a Leaf-bladed sword and a Lead-bladed battleaxe.', 'This is cumulative, the more players who participate the faster it will be.'),
  ('minor', null, 'Become the Rat King', 'Obtain 3 Scurrius spines.', 'This is cumulative, the more players who participate the faster it will be.'),
  ('minor', null, 'Wait... this doesn''t taste like milk...', 'Obtain 6 of any uniques from Brutus: Beef, Demonic Brutus slippers, Bottomless milk bucket, Mooleta, Regular Brutus slippers', 'This is cumulative, the more players who participate the faster it will be.');

insert into task (kind, tile_sequence, title, task, notes) values
  ('minor', null, 'My wrath prevails over my mercy', 'Obtain a Zombie axe or a Zombie helmet.', null),
  ('minor', null, 'Time to clock in at the Quarry', 'Obtain 2 of any of the following items: Granite helm, Granite body, Granite legs, Granite gloves, Granite boots, Granite shield, Granite ring, Granite maul, Granite longsword, Granite hammer', 'This is cumulative, the more players who participate the faster it will be.'),
  ('minor', null, 'Pog Slayer!!!', 'Obtain 6 of any Slayer collection-log uniques.', 'The list is massive, think of anything on the Slayer Collection-log or Slayer Boss specific logs. This task is cumulative, the more players who participate the faster it will be.'),
  ('minor', null, 'We''re all mad here', 'Obtain 6 Ardeaglais teleport scrolls.', 'This is cumulative, the more players who participate the faster it will be.'),
  ('minor', null, 'Dropping into a hot zone!', 'Obtain 6 Revenant teleport scrolls.', 'This is cumulative, the more players who participate the faster it will be.'),
  ('minor', null, 'I keep forgetting to bring my lantern...', 'Obtain 6 Guthixian Temple teleport scrolls.', 'This is cumulative, the more players who participate the faster it will be.'),
  ('minor', null, 'Zulrah used to drop 50 of these at one time!!! Okay Grandpa let''s get you back to bed...', 'Obtain 6 Zul-andra teleport scrolls.', 'This is cumulative, the more players who participate the faster it will be.'),
  ('minor', null, 'I really don''t want to do cardio...', 'Obtain 6 Mokhaiotl waystones.', 'This is cumulative, the more players who participate the faster it will be.'),
  ('minor', null, 'It''s so cold in here... Ouch that''s hot!', 'Obtain 2 Giantsoul amulets.', 'This is cumulative, the more players who participate the faster it will be.'),
  ('minor', null, 'If I just spoon the tbow I wouldn''t have to do all this...', 'Obtain the beginner raid weapon kit from scratch: 1 Rune crossbow, 1 Zombie axe, 1 Warped sceptre', null),
  ('minor', null, 'M'' Lady', 'Obtain a Fedora', null);
